# -*- coding: utf-8 -*-
"""Project_CheckIn_1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/14u62hPDKnOZ36ptafORcWWTpB4JCS19S
"""

class Hand():
  """Example class representing the Hand of one player 
        
        Attributes: 
          cards(str): A string of cards one player holds
          cards_sorted(str): A string of sorted cards one player holds
    """
  def __init__(self, cards, cards_sorted, rank, suit):
        self.cards = []
        self.cards_sorted = []
        self.rank = ['2', '3', '4', '5', '6', '7', '8', '9', '10', 'Jack', 'Queen', 'King', 'Ace']
        self.suit = ['Clubs', 'Diamonds', 'Hearts', 'Spades']

  def add_card(self, new_card):
        self.cards.append(new_card)
    
  def sort(self, deck, position):
         self.hand = deck[position::4]  
         hand = self.hand
   
  def value(self, key):  
       newHand = {}
       for i in self.hand:
         if i in key:
           newHand[i] = key[i]
       return newHand
