# -*- coding: utf-8 -*-
"""Project_CheckIn_1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/14u62hPDKnOZ36ptafORcWWTpB4JCS19S
"""

class Hand:
    def __init__(self, cards):
        self.cards = []
        self.cards_sorted = []